services:
  web:
    image: ghcr.io/matiuhart/vulnerable-web-app-eko:749e1964124f4b5bf628675538249621fbbc5999
    container_name: vulnerable-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
