services:
  web:
    image: ghcr.io/matiuhart/vulnerable-web-app-eko:1b1205e33620dd33b3e3bb4c7a571024e9789c1c
    container_name: vulnerable-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
