services:
  web:
    image: ghcr.io/matiuhart/vulnerable-web-app-eko:16598197532ee08a4d269a33c189e2da2fe2eee3
    container_name: vulnerable-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
