---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  labels:
    app: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-app
        image: ghcr.io/matiuhart/vulnerable-web-app-eko:sha-7e0d8837dbe758f3b198b744d7b42b78c810a4f2
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app-svc
  labels:
    app: vulnerable-app
spec:
  type: ClusterIP
  selector:
    app: vulnerable-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
  name: vulnerable-app
  namespace: eko
spec:
  ingressClassName: traefik
  rules:
  - host: matias-uhart.mtu-it.com.ar
    http:
      paths:
      - backend:
          service:
            name: vaultwarden
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - matias-uhart.mtu-it.com.ar
