---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  labels:
    app: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-app
        image: ghcr.io/matiuhart/vulnerable-web-app-eko:sha-d1177b5b67e896c4ac39e85d72743785d77a2abd
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app-svc
  namespace: eko-stg
  labels:
    app: vulnerable-app
spec:
  type: NodePort   # <--- Cambiado de ClusterIP a NodePort
  selector:
    app: vulnerable-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
      protocol: TCP
      name: http
